### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by PetrSixta** [taro-suite/taro#2]
When trying to run Taro through python Interpreter, Config File Not Found Error occurs.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/petr/taro/taroapp/__main__.py", line 42, in <module>
    main(sys.argv[1:])
  File "/home/petr/taro/taroapp/__main__.py", line 22, in main
    setup_config(args_ns)
  File "/home/petr/taro/taroapp/__main__.py", line 37, in setup_config
    argsconfig.load_config(args)
  File "/home/petr/taro/taroapp/argsconfig.py", line 10, in load_config
    cfgfile.load(get_config_file_path(args))
  File "/home/petr/taro/taroapp/argsconfig.py", line 19, in get_config_file_path
    return paths.lookup_config_file()
  File "/home/petr/taro/taro/paths.py", line 52, in lookup_config_file
    return lookup_config_file_path(DEFAULT_CONFIG_FILE)
  File "/home/petr/taro/taro/paths.py", line 87, in lookup_config_file_path
    raise FileNotFoundError('Config file not found in paths: ' + str([str(config) for config in paths]))
FileNotFoundError: Config file not found in paths: ['/etc/taro/taro.yaml']
```

**Comment by StanSvec** [comment]
Are you executing as **root** user? The config should be searched first in your home directory.

In any case the issue is caused by missing config file in the search path. This will affect anyone installing the app using pip, because I don't know how to configure setuptools to copy the config during installation. Seems like there is no easy solution for it.

Therefore what we need is a new command which will copy the config file into an appropriate location:
`taro config create`

**Comment by StanSvec** [comment]
This is how `taro config create` command must create the config file:
1. Get config search path by using `paths.config_file_search_path(exclude_cwd=True)`
2. Copy the config file into the first directory from the obtained list of paths returned by the function above
