### ISSUE TITLE
JSONDecodeError in taro tail command

### ISSUE THREAD

**Issue by StanSvec** [taro-suite/taro#9]
```
Exception in thread Thread-ApiServer:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/taro/socket.py", line 47, in serve
    req_body = json.loads(datagram)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1383 (char 1382)
```

**Comment by StanSvec** [comment]
Fixed
